
(function(){
  const DATA = window.APP_DATA || {cases:[], games:[]};
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const params = new URLSearchParams(location.search);
  const storeKey = 'familyMysteryHubProgressV2';
  const getProgress = () => JSON.parse(localStorage.getItem(storeKey) || '{"solved":{},"evidence":{},"hints":{}}');
  const setProgress = (p) => localStorage.setItem(storeKey, JSON.stringify(p));
  function toast(msg){ const el=$('#toast'); if(!el) return; el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); }
  function difficultyClass(d){ return d==='سهل'?'easy':d==='متوسط'?'medium':d==='صعب'?'hard':'expert'; }
  function setActiveNav(){ const page=document.body.dataset.page; $$('.navlinks a').forEach(a=>{ if(a.dataset.nav===page) a.classList.add('active') }); }
  function initNav(){ const btn=$('#mobileToggle'), links=$('#navlinks'); if(btn&&links) btn.addEventListener('click',()=>links.classList.toggle('open')); setActiveNav(); }
  function caseCard(c){ const solved = !!getProgress().solved[c.id]; return `<article class="case-card" data-diff="${c.difficulty}"><a href="case.html?id=${c.id}"><div class="case-cover"><img src="${c.cover}" alt="${c.title}"></div><div class="case-content"><h3>${c.title}</h3><p>${c.summary}</p><div class="tags"><span class="tag ${difficultyClass(c.difficulty)}">${c.difficulty}</span><span class="tag family">${c.age}</span>${solved?'<span class="tag easy">محلولة</span>':''}</div></div></a></article>`; }
  function renderHome(){ const featured=$('#featuredCases'); if(featured) featured.innerHTML=DATA.cases.slice(0,4).map(caseCard).join(''); const game=$('#featuredGames'); if(game) game.innerHTML=DATA.games.slice(0,5).map(g=>`<article class="game-card"><div class="game-icon">${g.icon}</div><h3>${g.title}</h3><p>${g.summary}</p><div class="tags"><span class="tag family">${g.difficulty}</span></div></article>`).join(''); }
  function renderCases(){ const grid=$('#casesGrid'); if(!grid) return; grid.innerHTML=DATA.cases.map(caseCard).join(''); $$('.filter').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const val=btn.dataset.filter; $$('.case-card').forEach(card=>{ card.style.display=(val==='all'||card.dataset.diff===val)?'block':'none'; }); })); }
  function renderCasePage(){
    const id=params.get('id') || DATA.cases[0]?.id; const c=DATA.cases.find(x=>x.id===id) || DATA.cases[0]; if(!c) return;
    document.title = c.title + ' | Family Mystery Hub';
    const progress=getProgress();
    $('#caseTitle') && ($('#caseTitle').textContent=c.title);
    $('#caseSummary') && ($('#caseSummary').textContent=c.summary);
    $('#caseCover') && ($('#caseCover').src=c.cover, $('#caseCover').alt=c.title);
    $('#caseMeta') && ($('#caseMeta').innerHTML=`<span class="tag ${difficultyClass(c.difficulty)}">${c.difficulty}</span><span class="tag family">${c.age}</span><span class="tag family">${c.duration}</span>`);
    const nav=$('#caseNav'); if(nav) nav.innerHTML=DATA.cases.map(x=>`<a class="${x.id===c.id?'active':''}" href="case.html?id=${x.id}">${x.title}<br><small>${x.difficulty}</small></a>`).join('');
    const tabs=$('#tabs'); const content=$('#caseContent');
    function drawSection(key){ const sec=c.sections.find(s=>s.key===key)||c.sections[0]; if(!content) return; $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.key===sec.key)); let inner=`<section class="reader-section"><h2>${sec.title}</h2>`; if(sec.body) inner+=sec.body.map(p=>`<p>${p}</p>`).join(''); if(sec.items) inner+=`<ul>${sec.items.map(i=>`<li>${i}</li>`).join('')}</ul>`; if(sec.cards) inner+=`<div class="evidence-grid">${sec.cards.map(card=>`<div class="evidence-card"><b>${card.name}</b><span>${card.text}</span></div>`).join('')}</div>`; inner+=`<div class="quote">الدليل القابل للإضافة: ${sec.evidence}</div><button class="btn btn-primary" id="addEvidenceBtn">أضف هذا الدليل</button></section>`; content.innerHTML=inner; $('#addEvidenceBtn')?.addEventListener('click',()=>addEvidence(c.id,sec.evidence)); }
    if(tabs) { tabs.innerHTML=c.sections.map((s,i)=>`<button class="tab ${i===0?'active':''}" data-key="${s.key}">${s.title}</button>`).join(''); $$('.tab').forEach(t=>t.addEventListener('click',()=>drawSection(t.dataset.key))); }
    const select=$('#answerSelect'); if(select) select.innerHTML=c.options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
    $('#minEvidence') && ($('#minEvidence').textContent=c.minEvidence);
    drawBoard(c.id); drawHints(c); drawSection(c.sections[0]?.key);
    $('#solveBtn')?.addEventListener('click',()=>solveCase(c));
    $('#resetCase')?.addEventListener('click',()=>{ const p=getProgress(); delete p.evidence[c.id]; delete p.solved[c.id]; delete p.hints[c.id]; setProgress(p); drawBoard(c.id); drawHints(c); $('#result').className='result'; $('#result').textContent=''; toast('تم تصفير تقدم القضية'); });
  }
  function addEvidence(id,text){ const p=getProgress(); p.evidence[id]=p.evidence[id]||[]; if(!p.evidence[id].includes(text)) p.evidence[id].push(text); setProgress(p); drawBoard(id); toast('تمت إضافة الدليل'); }
  function drawBoard(id){ const board=$('#board'); if(!board) return; const ev=(getProgress().evidence[id]||[]); board.innerHTML=ev.length?ev.map((e,i)=>`<div class="note"><b>دليل ${i+1}</b><br>${e}</div>`).join(''):'<div class="note">لم تجمع أدلة بعد. افتح التبويبات واضغط “أضف هذا الدليل”.</div>'; const count=$('#evidenceCount'); if(count) count.textContent=ev.length; }
  function drawHints(c){ const box=$('#hintBox'); if(!box) return; const p=getProgress(); const used=p.hints[c.id]||0; box.innerHTML= used? c.hints.slice(0,used).map((h,i)=>`<div class="note"><b>هنت ${i+1}</b><br>${h}</div>`).join('') : '<div class="note">لم تستخدم أي هنت بعد.</div>'; $('#hintCount') && ($('#hintCount').textContent=used); $('#hintBtn') && ($('#hintBtn').onclick=()=>{ const pp=getProgress(); const n=Math.min((pp.hints[c.id]||0)+1,c.hints.length); pp.hints[c.id]=n; setProgress(pp); drawHints(c); toast(n===c.hints.length?'هذا آخر هنت':'تم فتح هنت جديد'); }); }
  function solveCase(c){ const p=getProgress(); const ev=(p.evidence[c.id]||[]); const res=$('#result'); const ans=$('#answerSelect')?.value; if(ev.length<c.minEvidence){ res.className='result bad'; res.innerHTML=`لا يمكن إرسال التقرير الآن. اجمع ${c.minEvidence} أدلة على الأقل. لديك حاليًا ${ev.length}.`; return; } if(ans===c.solution){ p.solved[c.id]=true; setProgress(p); res.className='result good'; res.innerHTML=`<b>تحليل صحيح.</b><br>${c.success}`; toast('تم حل القضية'); } else { res.className='result bad'; res.innerHTML='<b>استنتاج غير دقيق.</b><br>راجع الأدلة والشهادات. غالبًا يوجد تناقض صغير يقود للحل.'; } }
  function renderGames(){ const grid=$('#gamesGrid'); if(!grid) return; grid.innerHTML=DATA.games.map(g=>`<article class="game-card"><div class="game-icon">${g.icon}</div><h3>${g.title}</h3><p>${g.summary}</p><button class="btn btn-primary" data-game="${g.id}">ابدأ</button></article>`).join(''); $$('[data-game]').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.game))); openGame('memory'); }
  function openGame(id){ const area=$('#gameArea'); if(!area) return; const game=DATA.games.find(g=>g.id===id); if(!game) return; if(id==='memory') return memoryGame(area); if(id==='timeline') return timelineGame(area); if(id==='code') return codeGame(area); if(id==='word') return wordGame(area); if(id==='logic') return logicGame(area); }
  function memoryGame(area){ const icons=['🚲','🏺','📚','🗝️','🚲','🏺','📚','🗝️'].sort(()=>Math.random()-.5); let open=[],matched=0,moves=0; area.innerHTML='<h2>لعبة الذاكرة</h2><p class="lead">اعثر على الأزواج المتشابهة.</p><div class="memory-grid"></div><div id="gameMsg" class="quote">المحاولات: 0</div>'; const grid=$('.memory-grid',area); icons.forEach((ic,i)=>{ const d=document.createElement('button'); d.className='mem-card'; d.textContent='؟'; d.onclick=()=>{ if(d.classList.contains('open')||open.length===2) return; d.classList.add('open'); d.textContent=ic; open.push([d,ic]); if(open.length===2){ moves++; $('#gameMsg').textContent='المحاولات: '+moves; setTimeout(()=>{ if(open[0][1]===open[1][1]){ matched+=2; if(matched===icons.length) $('#gameMsg').textContent='رائع! أنهيت اللعبة في '+moves+' محاولات.'; } else { open[0][0].classList.remove('open'); open[1][0].classList.remove('open'); open[0][0].textContent='؟'; open[1][0].textContent='؟'; } open=[]; },650); } }; grid.appendChild(d); }); }
  function timelineGame(area){ const correct=['دخل سامر الدراجة للمخزن','ذهب سامر للتسجيل','غادر عامل التوصيل','اختفت الدراجة','ظهرت كذبة المطر']; let selected=[]; area.innerHTML='<h2>رتب الأحداث</h2><p class="lead">اضغط الأحداث بالترتيب الصحيح.</p><div class="sortable-list"></div><button class="btn btn-primary" id="checkOrder">تحقق</button><div id="gameMsg" class="quote">اختر بالترتيب.</div>'; const list=$('.sortable-list',area); [...correct].sort(()=>Math.random()-.5).forEach(t=>{ const b=document.createElement('button'); b.className='sort-item'; b.textContent=t; b.onclick=()=>{ if(selected.includes(t))return; selected.push(t); b.classList.add('selected'); b.textContent=selected.length+' - '+t; }; list.appendChild(b); }); $('#checkOrder').onclick=()=>{ $('#gameMsg').textContent=JSON.stringify(selected)===JSON.stringify(correct)?'صحيح! ترتيب منطقي ممتاز.':'راجع الترتيب وحاول مرة أخرى.'; }; }
  function codeGame(area){ area.innerHTML='<h2>كسر الرمز</h2><p class="lead">الرمز من 3 أرقام. الرقم الأول هو عدد القضايا السهلة، الثاني عدد القضايا الخبيرة، الثالث عدد ألعاب العائلة.</p><input class="input" id="codeInput" placeholder="اكتب الرمز"><button class="btn btn-primary" id="checkCode">تحقق</button><div id="gameMsg" class="quote">تلميح: احسب من الموقع.</div>'; $('#checkCode').onclick=()=>{ $('#gameMsg').textContent=$('#codeInput').value.trim()==='225'?'صحيح! الرمز هو 225.':'ليس صحيحًا. القضايا السهلة 2، الخبيرة 1، الألعاب 5.'; }; }
  function wordGame(area){ area.innerHTML='<h2>كلمة السر</h2><p class="lead">أنا شيء يجمعه المحقق، لا يتكلم لكنه يوضح الحقيقة. ما أنا؟</p><input class="input" id="wordInput" placeholder="اكتب الإجابة"><button class="btn btn-primary" id="checkWord">تحقق</button><div id="gameMsg" class="quote">تلميح: موجود في لوحة التحقيق.</div>'; $('#checkWord').onclick=()=>{ const v=$('#wordInput').value.trim(); $('#gameMsg').textContent=(v.includes('دليل')||v.includes('الأدلة'))?'صحيح! الإجابة هي الدليل.':'قريب؟ فكر في شيء يضاف للوحة التحقيق.'; }; }
  function logicGame(area){ area.innerHTML='<h2>تحدي المنطق</h2><p class="lead">ثلاثة أطفال: علي، نور، ياسين. واحد فقط أخذ الكرة. علي قال: نور أخذتها. نور قالت: لم آخذها. ياسين قال: علي يكذب. إذا كان واحد فقط يقول الحقيقة، فمن أخذ الكرة؟</p><select id="logicAns"><option value="">اختر</option><option value="ali">علي</option><option value="noor">نور</option><option value="yassin">ياسين</option></select><button class="btn btn-primary" id="checkLogic">تحقق</button><div id="gameMsg" class="quote">حلها بالصدق والكذب.</div>'; $('#checkLogic').onclick=()=>{ $('#gameMsg').textContent=$('#logicAns').value==='ali'?'صحيح! لو علي أخذ الكرة: كلام علي كذب، نور صادقة، ياسين صادق؟ لا، يصبح اثنان. أعد التفكير! الإجابة الصحيحة هنا نور؟ انتبه.' : 'الإجابة المنطقية: نور. عندها علي صادق، نور كاذبة، وياسين كاذب، إذن واحد فقط صادق.'; if($('#logicAns').value==='noor') $('#gameMsg').textContent='صحيح! نور أخذت الكرة: علي صادق، نور كاذبة، ياسين كاذب.'; }; }
  function renderGuide(){ const progress=$('#progressSummary'); if(!progress) return; const p=getProgress(); const solved=Object.keys(p.solved||{}).length; progress.innerHTML=`<div class="progress-pill">قضايا محلولة: ${solved}</div><div class="progress-pill">إجمالي القضايا: ${DATA.cases.length}</div><div class="progress-pill">الألعاب: ${DATA.games.length}</div>`; $('#clearProgress')?.addEventListener('click',()=>{localStorage.removeItem(storeKey); location.reload();}); }
  document.addEventListener('DOMContentLoaded',()=>{ initNav(); renderHome(); renderCases(); renderCasePage(); renderGames(); renderGuide(); });
})();
