const $ = (sel, root=document) => root.querySelector(sel);
const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];
const STORE_KEY = 'familyMysteryHubPro';
function getStore(){ try { return JSON.parse(localStorage.getItem(STORE_KEY)) || { solved:{}, evidence:{}, hints:{}}; } catch { return { solved:{}, evidence:{}, hints:{}}; } }
function setStore(data){ localStorage.setItem(STORE_KEY, JSON.stringify(data)); }
function toast(message){ let t=$('#toast'); if(!t){ t=document.createElement('div'); t.id='toast'; t.className='toast'; document.body.appendChild(t);} t.textContent=message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2200); }
function initNav(){ const page=document.body.dataset.page; $$('.main-nav a').forEach(a=>{ if(a.dataset.page===page) a.classList.add('active'); }); const btn=$('#menuToggle'); if(btn) btn.addEventListener('click',()=>$('.main-nav').classList.toggle('open')); }
function difficultyClass(level){ if(level<=1) return 'level-1'; if(level===2) return 'level-2'; if(level===3) return 'level-3'; if(level===4) return 'level-4'; return 'level-5'; }
function caseCard(c){ const store=getStore(); const solved=store.solved[c.id]; return `<a class="case-card pro-card" href="case.html?id=${c.id}" data-level="${c.level}"><img src="${c.cover}" alt="${c.title}"><div class="case-card-content"><div class="tags"><span class="tag ${difficultyClass(c.level)}">${c.difficulty}</span><span class="tag">${c.age}</span>${solved?'<span class="tag">تم الحل ✓</span>':''}</div><h3>${c.icon} ${c.title}</h3><p>${c.summary}</p><div class="tags"><span class="tag">${c.category}</span><span class="tag">${c.time}</span></div></div></a>`; }
function renderHome(){ if(!window.CASES) return; const featured=$('#featuredCases'); if(featured) featured.innerHTML=CASES.slice(0,4).map(caseCard).join(''); const solved=$('#solvedCount'); if(solved){ const store=getStore(); solved.textContent=Object.keys(store.solved||{}).length; } const homeGames=$('#homeGames'); if(homeGames && window.GAMES){ homeGames.innerHTML=GAMES.map(g=>`<a class="mini-game-card pro-card" href="games.html#${g.id}"><span>${g.icon}</span><b>${g.title}</b><p class="muted">${g.subtitle}</p></a>`).join(''); } }
function renderCases(){ const grid=$('#casesGrid'); if(!grid || !window.CASES) return; grid.innerHTML=CASES.map(caseCard).join(''); $$('.filter').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const f=btn.dataset.filter; $$('.case-card',grid).forEach(card=>{ const lv=Number(card.dataset.level); card.style.display = f==='all' || (f==='5'?lv>=5:lv===Number(f)) ? '' : 'none'; }); })); }
function boot(){ initNav(); renderHome(); renderCases(); }
document.addEventListener('DOMContentLoaded', boot);
