let currentCase, currentTab, hintIndex=0;
function caseIdFromUrl(){ return new URLSearchParams(location.search).get('id') || 'museum'; }
function initCasePage(){ if(!window.CASES) return; currentCase = CASES.find(c=>c.id===caseIdFromUrl()) || CASES[0]; currentTab = currentCase.sections[0].id; renderCaseShell(); renderTabs(); renderTab(); renderBoard(); }
function storeCase(){ const store=getStore(); store.evidence[currentCase.id] ||= []; store.hints[currentCase.id] ||= 0; return store; }
function renderCaseShell(){ $('#caseCover').src=currentCase.cover; $('#caseName').textContent=currentCase.title; $('#caseTitle').textContent=currentCase.title; $('#caseSummary').textContent=currentCase.summary; $('#caseLevel').textContent=`${currentCase.difficulty} • مستوى ${currentCase.level}`; $('#caseMeta').textContent=`${currentCase.category} • ${currentCase.age} • وقت تقديري: ${currentCase.time}`; $('#answerSelect').innerHTML=currentCase.options.map(o=>`<option value="${o[0]}">${o[1]}</option>`).join(''); $('#hintBtn').onclick=openHint; $('#nextHintBtn').onclick=nextHint; $('#closeHintBtn').onclick=closeHint; $('#solveBtn').onclick=solveCase; $('#resetCaseBtn').onclick=resetCase; }
function renderTabs(){ $('#caseTabs').innerHTML=currentCase.sections.map(s=>`<button class="tab ${s.id===currentTab?'active':''}" data-id="${s.id}">${s.title}</button>`).join(''); $$('#caseTabs .tab').forEach(b=>b.onclick=()=>{ currentTab=b.dataset.id; renderTabs(); renderTab(); }); }
function renderTab(){ const s=currentCase.sections.find(x=>x.id===currentTab); const suspects = currentTab==='file' ? `<div class="info-grid">${currentCase.suspects.map(x=>`<div class="info-tile"><b>${x.name}</b><span>${x.detail}</span></div>`).join('')}</div>` : ''; $('#caseContent').innerHTML = `<h2>${s.title}</h2>${s.body.map(p=>p.includes(':') && !p.startsWith('http') ? `<p>${p}</p>` : `<p>${p}</p>`).join('')}<div class="info-tile"><b>دليل هذا التبويب</b><span>${s.evidence}</span></div>${suspects}<button class="btn primary" style="margin-top:16px" onclick="addEvidence('${s.id}')">إضافة هذا الدليل</button>`; }
function addEvidence(id=currentTab){ const s=currentCase.sections.find(x=>x.id===id); const store=storeCase(); if(!store.evidence[currentCase.id].includes(id)){ store.evidence[currentCase.id].push(id); setStore(store); toast('تمت إضافة الدليل'); } else toast('الدليل موجود بالفعل'); renderBoard(); }
function renderBoard(){ const store=storeCase(); const ids=store.evidence[currentCase.id] || []; const needed=currentCase.requiredEvidence; $('#progressBar').style.width=Math.min(100, Math.round(ids.length/needed*100))+'%'; $('#progressText').textContent=`${ids.length} من ${needed} أدلة مطلوبة قبل التقرير.`; $('#evidenceBoard').innerHTML = ids.length ? ids.map(id=>{ const s=currentCase.sections.find(x=>x.id===id); return `<div class="evidence-note"><b>${s.title}</b><br>${s.evidence}</div>`; }).join('') : '<div class="evidence-note">لم تضف أي دليل بعد. افتح التبويبات واضغط إضافة الدليل.</div>'; }
function openHint(){ const store=storeCase(); hintIndex=store.hints[currentCase.id]||0; $('#hintText').textContent=currentCase.hints[Math.min(hintIndex,currentCase.hints.length-1)]; $('#hintModal').classList.add('show'); }
function nextHint(){ const store=storeCase(); store.hints[currentCase.id]=Math.min((store.hints[currentCase.id]||0)+1,currentCase.hints.length-1); setStore(store); hintIndex=store.hints[currentCase.id]; $('#hintText').textContent=currentCase.hints[hintIndex]; }
function closeHint(){ $('#hintModal').classList.remove('show'); }
function solveCase(){ const val=$('#answerSelect').value; const store=storeCase(); const ids=store.evidence[currentCase.id] || []; const result=$('#caseResult'); if(ids.length < currentCase.requiredEvidence){ result.className='result-box bad'; result.innerHTML=`<b>التحقيق ناقص.</b><br>لازم تجمع ${currentCase.requiredEvidence} أدلة على الأقل قبل التقرير. لديك الآن ${ids.length}.`; return; } if(val===currentCase.solution){ store.solved[currentCase.id]={date:new Date().toISOString(), notes:$('#noteBox').value}; setStore(store); result.className='result-box good'; result.innerHTML=`<b>تقرير صحيح!</b><br>${currentCase.solutionText}`; } else { result.className='result-box bad'; result.innerHTML='<b>استنتاج غير دقيق.</b><br>راجع لوحة الأدلة والهنتات. الحل يعتمد على ربط الفرصة بالدافع والدليل الحاسم.'; } }
function resetCase(){ const store=getStore(); if(store.evidence) store.evidence[currentCase.id]=[]; if(store.hints) store.hints[currentCase.id]=0; if(store.solved) delete store.solved[currentCase.id]; setStore(store); $('#caseResult').className='result-box'; $('#noteBox').value=''; $('#answerSelect').value=''; renderBoard(); toast('تمت إعادة القضية'); }
document.addEventListener('DOMContentLoaded', initCasePage);
