let activeGame='memory'; let memoryState={first:null,lock:false,matched:0};
function initGames(){ if(location.hash) activeGame=location.hash.slice(1); renderGameMenu(); renderGame(); }
function renderGameMenu(){ const menu=$('#gameMenu'); menu.innerHTML=GAMES.map(g=>`<button class="game-choice ${g.id===activeGame?'active':''}" data-id="${g.id}"><b>${g.icon} ${g.title}</b><small>${g.subtitle}</small></button>`).join(''); $$('.game-choice',menu).forEach(b=>b.onclick=()=>{ activeGame=b.dataset.id; location.hash=activeGame; renderGameMenu(); renderGame(); }); }
function renderGame(){ const stage=$('#gameStage'); if(activeGame==='memory') return renderMemory(stage); if(activeGame==='timeline') return renderTimeline(stage); if(activeGame==='code') return renderCode(stage); if(activeGame==='words') return renderWords(stage); renderLogic(stage); }
function renderMemory(stage){ const icons=['🏺','🏺','🚲','🚲','🗝️','🗝️','📚','📚','🧭','🧭','⭐','⭐']; icons.sort(()=>Math.random()-.5); memoryState={first:null,lock:false,matched:0}; stage.innerHTML=`<h2>🧠 لعبة الذاكرة</h2><p class="muted">اعثر على كل الأزواج المتشابهة.</p><div class="memory-grid">${icons.map((x,i)=>`<button class="memory-card" data-icon="${x}" data-i="${i}">؟</button>`).join('')}</div><div id="gameResult" class="result-box"></div>`; $$('.memory-card').forEach(card=>card.onclick=()=>flipCard(card)); }
function flipCard(card){ if(memoryState.lock || card.classList.contains('done') || card.textContent!=='؟') return; card.textContent=card.dataset.icon; if(!memoryState.first){ memoryState.first=card; return; } if(memoryState.first.dataset.icon===card.dataset.icon){ card.classList.add('done'); memoryState.first.classList.add('done'); memoryState.first=null; memoryState.matched+=2; if(memoryState.matched===12){ const r=$('#gameResult'); r.className='result-box good'; r.innerHTML='<b>ممتاز!</b><br>أنهيت لعبة الذاكرة.'; } } else { memoryState.lock=true; setTimeout(()=>{card.textContent='؟'; memoryState.first.textContent='؟'; memoryState.first=null; memoryState.lock=false;},650); } }
function renderTimeline(stage){ const events=['وصلت اللوحة للمعرض','تعطلت الكاميرا الخلفية','فُتح باب المخزن مرة واحدة','اكتُشف اختفاء اللوحة']; const shuffled=[...events].sort(()=>Math.random()-.5); stage.innerHTML=`<h2>🧩 رتب الأحداث</h2><p class="muted">اضغط على الأحداث بالترتيب الصحيح.</p><div class="puzzle-list">${shuffled.map(e=>`<button class="puzzle-item">${e}</button>`).join('')}</div><button class="btn primary" id="checkTimeline">تحقق</button><button class="btn ghost" onclick="renderTimeline($('#gameStage'))">إعادة</button><div id="gameResult" class="result-box"></div>`; const chosen=[]; $$('.puzzle-item').forEach(btn=>btn.onclick=()=>{ if(btn.classList.contains('selected')) return; btn.classList.add('selected'); chosen.push(btn.textContent); btn.textContent=chosen.length+' - '+btn.textContent; }); $('#checkTimeline').onclick=()=>{ const ok=events.every((e,i)=>chosen[i]===e); const r=$('#gameResult'); r.className='result-box '+(ok?'good':'bad'); r.innerHTML=ok?'<b>صحيح!</b><br>ترتيبك منطقي.':'<b>حاول مرة أخرى.</b><br>راجع بداية الأحداث ونهايتها.'; }; }
function renderCode(stage){ stage.innerHTML=`<h2>🔐 كسر الرمز</h2><p class="muted">التلميحات: الرقم الأول هو عدد عجلات الدراجة. الرقم الثاني عدد حروف كلمة فن. الرقم الثالث عدد نجوم الشعار.</p><div class="input-row"><input id="codeInput" placeholder="اكتب الكود من 3 أرقام"><button class="btn primary" id="checkCode">تحقق</button></div><div id="gameResult" class="result-box"></div>`; $('#checkCode').onclick=()=>{ const ok=$('#codeInput').value.trim()==='223'; const r=$('#gameResult'); r.className='result-box '+(ok?'good':'bad'); r.innerHTML=ok?'<b>تم فتح القفل!</b><br>الكود هو 223.':'<b>غير صحيح.</b><br>فكر في كل تلميح كرقم مستقل.'; }; }
function renderWords(stage){ stage.innerHTML=`<h2>🔎 كلمة السر</h2><p class="muted">رتب الحروف لتكوين كلمة مرتبطة بالتحقيق: ة ل د أ</p><div class="input-row"><input id="wordInput" placeholder="الكلمة"><button class="btn primary" id="checkWord">تحقق</button></div><div id="gameResult" class="result-box"></div>`; $('#checkWord').onclick=()=>{ const v=$('#wordInput').value.trim().replace('أ','ا'); const ok=v==='ادلة' || v==='دليل'; const r=$('#gameResult'); r.className='result-box '+(ok?'good':'bad'); r.innerHTML=ok?'<b>صحيح!</b><br>الأدلة هي قلب أي قضية.':'<b>قريب.</b><br>الكلمة تعني Clues.'; }; }
function renderLogic(stage){ stage.innerHTML=`<h2>💡 تحدي المنطق</h2><p class="muted">سؤال: إذا كان أحمد أطول من سليم، وسلمى أقصر من سليم، فمن الأطول؟</p><div class="puzzle-list"><button class="puzzle-item" data-ok="1">أحمد</button><button class="puzzle-item">سليم</button><button class="puzzle-item">سلمى</button></div><div id="gameResult" class="result-box"></div>`; $$('.puzzle-item').forEach(b=>b.onclick=()=>{ const r=$('#gameResult'); r.className='result-box '+(b.dataset.ok?'good':'bad'); r.innerHTML=b.dataset.ok?'<b>إجابة صحيحة!</b><br>أحمد أطول من سليم، وسلمى أقصر من سليم.':'<b>غير صحيح.</b><br>اقرأ العلاقات مرة أخرى.'; }); }
document.addEventListener('DOMContentLoaded', initGames);
